/*
 * Copyright (c) 2022 NetEase, Inc. All rights reserved.
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 *
 */

export class AppConfig {
  // appKey 和 userName 在网易云信控制台获取
  // appKey 网易云信应用appkey
  public static appKey: string = '3e215d27b6a6a9e27dad7ef36dd5b65c'
  // userName 网易云信应用下账号ID
  public static userId: string = '332103880306944'
  // userName 网易云信应用下账号Token
  public static userToken: string = '2d9770b3-1b02-4b67-bbe1-851b522294e8'
}