/*
 * Copyright (c) 2022 NetEase, Inc. All rights reserved.
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 *
 */


export class AppConfig {
  // appKey 和 userName 在网易云信控制台获取
  // appKey 网易云信应用appkey
  public static appKey: string = ''
  // userName 网易云信应用下账号ID
  public static userId: string = ''
  // userName 网易云信应用下账号Token
  public static userToken: string = ''
}