/*
 * Copyright (c) 2022 NetEase, Inc. All rights reserved.
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 *
 */

/**
 * Route constants for Router.
 */
export class RouteConstants {
  /**
   * Route of page for the ResponsiveLayout.
   */
  static readonly RESPONSIVE_ROUTE: string = 'pages/ResponsiveIndex';
  /**
   * Route of page for the AdaptiveLayout.
   */
  static readonly ADAPTIVE_ROUTE: string = 'pages/AdaptiveIndex';
  /**
   * Route of page for the SystemCapabilities.
   */
  static readonly SYSTEM_CAPABILITIES_ROUTE: string = 'pages/SystemCapabilitiesIndex';
}