/*
 * Copyright (c) 2022 NetEase, Inc. All rights reserved.
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 *
 */

import BuildProfile from './BuildProfile'

export { LoginIndexPage as LoginIndex } from './src/main/ets/components/LoginIndexPage'

export { LoginIndexComponent } from './src/main/ets/components/LoginIndexPage'

export { LoginConfig } from './src/main/ets/config/LoginConfig'

export { AuthService, LoginInfo, OnLoginSuccess } from './src/main/ets/AuthService'

export { BuildProfile }
